apiVersion: v2
name: argo-cd
type: application
version: 1.0.0
dependencies:
  - name: argo-cd
    alias: app
    # keep in sync with kube/apps/argocd/terraform/bootstrap/variables.tf version
    version: 9.4.1
    repository: https://argoproj.github.io/argo-helm
  - name: idp-app
    alias: config
    version: 5.3.0
    repository: https://matuszeman.github.io/charts
  - name: idp-app
    alias: gateway
    version: 5.3.0
    repository: https://matuszeman.github.io/charts