app:
  #fullnameOverride: argocd
  configs:
    params:
      # we access server using ingress over https, but on http server port.
      # if insecure=false, argocd server would try to redirect to https even we access it on https via ingress.
      server.insecure: true
      # https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/#reconfigure-argo-cd-to-allow-certain-namespaces
      application.namespaces: "*"
      # https://argo-cd.readthedocs.io/en/latest/operator-manual/applicationset/Appset-Any-Namespace/#reconfigure-argo-cd-to-allow-certain-namespaces
      applicationsetcontroller.namespaces: "*"
      applicationsetcontroller.enable.scm.providers: false
  applicationSet:
    allowAnyNamespace: true
  dex:
    enabled: false

  server:
    ingress:
      # use gateway idp-app for ingress/http-route configuration
      enabled: false

config:
  appName: argocd
  appVersion: "v3.3.0"
#  configs:
#    hml-cl1:
#      templated: true
#      secret: {}
#      values:
#        name: hml-cl1
#        server: https://kubernetes.default.svc
#        config:
#          tlsClientConfig:
#            insecure: false
#      labels:
#        argocd.argoproj.io/secret-type: cluster
#      content:
#        name: '{{ .configSpec.values.name }}'
#        server: '{{ .configSpec.values.server }}'
#        config: '{{ toPrettyJson .configSpec.values.config }}'

gateway:
  appName: argocd-gateway
  appVersion: 1.0.0