apiVersion: v2
name: csi-longhorn
type: application
version: 1.0.0
dependencies:
  - name: longhorn
    alias: app
    version: 1.12.0
    repository: https://charts.longhorn.io
  - name: idp-app
    alias: config
    version: 5.15.0
    repository: https://matuszeman.github.io/charts
  - name: idp-app
    alias: gateway
    version: 5.15.0
    repository: https://matuszeman.github.io/charts