apiVersion: v2
name: csi-longhorn
type: application
version: 1.0.0
dependencies:
  - name: longhorn
    alias: app
    version: 1.11.0
    repository: https://charts.longhorn.io
  - name: idp-app
    alias: config
    version: 4.1.0
    repository: https://matuszeman.github.io/charts