cluster: _
idpAppConfig:
  clusters:
    _: {}
  defaults:
    configs:
      annotations: {}

# https://github.com/sergelogvinov/proxmox-csi-plugin/blob/main/docs/install.md#prepare-kubernetes-cluster
app:
  nameOverride: csi-proxmox
  fullnameOverride: csi-proxmox

  existingConfigSecret: csi-proxmox-config-secret
  existingConfigSecretKey: config.yaml

  config:
    # so it does not generate own config secret - we use idp-app for configs
    clusters: []

config:
  appName: csi-proxmox
  appVersion: 1.0.0
  configs:
    # https://github.com/sergelogvinov/proxmox-csi-plugin/blob/main/docs/install.md#install-the-plugin-by-using-kubectl
    secret:
      #secret: {}
      content:
        config.yaml: null