apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: ${name}
spec:
  encryptedData:
    #%{ for key, val in encrypted_data }
    ${key}: ${val}
    #%{ endfor }
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: ${name}
