apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ${name}
spec:
  acme:
    email: ${email}
    server: ${server}
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: ${release}-${name}-issuer-account
    solvers:
      - dns01:
          cloudflare:
            email: ${cloudflare.email}
            apiTokenSecretRef:
              name: ${secret_name}
              key: cloudflare_api_token