# https://artifacthub.io/packages/helm/traefik/traefik/9.2.0
# https://github.com/traefik/traefik-helm-chart/tree/master/traefik
app:
  global:
    checkNewVersion: false
  experimental:
    # -- Defines whether all plugins must be loaded successfully for Traefik to start
    abortOnPluginFailure: true
  gateway:
    enabled: false
  service:
    spec:
      externalTrafficPolicy: Local